### ISSUE TITLE
[Issues-003] JS 관련

### ISSUE THREAD

**Issue by qq8721443** [junh0328/prepare_frontend_interview#13]
## 📄 이슈 내용
- 데이터 타입에 BigInt 타입이 누락되어 있습니다.

## 📝 상세 내용
- 누락된 타입을 추가했습니다.

## ✔ 체크리스트
- [x] 해당 내용 내부에 목차를 추가하셨나요?
- [x] 최종적으로 readme 에도 목차를 추가하셨나요?

모두 확인하시고 체크를 눌러주세요 😁

**Comment by junh0328** [comment]
PR 확인하고 머지하였습니다. 감사합니다 :)
