### ISSUE TITLE
[Issues-004] CSS 관련

### ISSUE THREAD

**Issue by GeonWooPaeng** [junh0328/prepare_frontend_interview#16]
## 📄 이슈 내용
- 이슈 내용 요약 설명
CSS의 position의 속성에 대해서 부분 sticky 추가

## 📝 상세 내용
- 이슈 내용 구현 관련 상세 내용 작성

## ✔ 체크리스트
- [x] 해당 내용 내부에 목차를 추가하셨나요?
- [x] 최종적으로 readme 에도 목차를 추가하셨나요?

모두 확인하시고 체크를 눌러주세요 😁

**Comment by junh0328** [comment]
PR 바탕으로 내용 머지했습니다 감사합니다 👍🏼
